name: Upload html

on:
  push:
    branches: [ branch ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v3
     - run: create-pull-request/main
